#!/usr/bin/env node
// Maintainer commands for the native packaging layer.
//
//   mobile.mjs sync      copy the canonical dist/ into the Android and iOS projects, then verify
//   mobile.mjs verify    prove the packaged web content equals dist/ (hash manifests)
//   mobile.mjs verify-package <file.apk|file.aab>   prove a BUILT package embeds exactly dist/
//   mobile.mjs info      print the reproducibility record (course, Ono-Sendai pin, Capacitor, SDKs, build numbers)
//   mobile.mjs version   write version.properties + Xcode version settings from course-lock.yaml
//   mobile.mjs version --check   fail if they are out of date
//
// Mobile packages are consumers of the normal generated course artifact. Nothing here renders,
// rewrites or post-processes course content.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  DIST, MOBILE, PLATFORM_WEB, buildNumbers, compareManifests, manifest, manifestDigest,
  readLock, readVersionJson, requireDist, summarize,
} from './lib.mjs';

const PBXPROJ = join(MOBILE, 'ios/App/App.xcodeproj/project.pbxproj');
const VERSION_PROPS = join(MOBILE, 'version.properties');

function versionFiles() {
  const lock = readLock();
  const rev = readVersionJson().buildRevision;
  const code = buildNumbers(lock.courseVersion, rev);
  const props =
    '# Generated by `mobile/tools/mobile.mjs version` from course-lock.yaml and version.json. Do not edit.\n' +
    `versionName=${lock.courseVersion}\nversionCode=${code}\n`;
  let pbx = readFileSync(PBXPROJ, 'utf8');
  pbx = pbx.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${lock.courseVersion};`)
    .replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${code};`);
  return { props, pbx };
}

function cmdVersion(check) {
  const { props, pbx } = versionFiles();
  const stale = [];
  if (!existsSync(VERSION_PROPS) || readFileSync(VERSION_PROPS, 'utf8') !== props) stale.push('mobile/version.properties');
  if (readFileSync(PBXPROJ, 'utf8') !== pbx) stale.push('mobile/ios/App/App.xcodeproj/project.pbxproj');
  if (check) {
    if (stale.length) throw new Error(`version metadata out of date (run \`make mobile-version\`): ${stale.join(', ')}`);
    console.log('version metadata matches course-lock.yaml');
    return;
  }
  writeFileSync(VERSION_PROPS, props);
  writeFileSync(PBXPROJ, pbx);
  console.log(`version metadata written: ${props.trim().split('\n').slice(1).join(' ')}`);
}

function cmdVerify({ quiet = false } = {}) {
  requireDist();
  const canonical = manifest(DIST);
  let checked = 0;
  const problems = [];
  for (const [platform, dir] of Object.entries(PLATFORM_WEB)) {
    if (!existsSync(dir)) {
      // A platform copy that was never synchronised is not "stale"; it is absent. Android is
      // mandatory on every host, iOS is optional (the copy is created by `cap sync` anywhere).
      problems.push(`${platform}: no synchronised web copy at ${dir} (run \`make mobile-sync\`)`);
      continue;
    }
    checked++;
    for (const p of compareManifests(canonical, manifest(dir))) problems.push(`${platform}: ${p}`);
  }
  if (problems.length) {
    throw new Error(`packaged web content does not match dist/:\n  ${summarize(problems)}`);
  }
  const digest = manifestDigest(canonical);
  if (!quiet) console.log(`content equivalence OK: ${Object.keys(canonical).length} files, manifest sha256:${digest} (${checked} platform copies)`);
  return digest;
}

// A built APK/AAB is a zip: the web content lives under assets/public (APK) or base/assets/public (AAB).
function cmdVerifyPackage(file) {
  if (!file || !existsSync(file)) throw new Error('usage: mobile.mjs verify-package <file.apk|file.aab>');
  requireDist();
  const tmp = mkdtempSync(join(tmpdir(), 'rrc-pkg-'));
  try {
    const r = spawnSync('unzip', ['-q', '-o', file, 'assets/public/*', 'base/assets/public/*', '-d', tmp], { encoding: 'utf8' });
    if (r.status !== 0 && r.status !== 11) throw new Error(`unzip failed: ${r.stderr}`); // 11: one of the two patterns matched nothing
    const root = [join(tmp, 'assets/public'), join(tmp, 'base/assets/public')].find(existsSync);
    if (!root) throw new Error(`${file} contains no assets/public: not a Capacitor package`);
    const problems = compareManifests(manifest(DIST), manifest(root));
    if (problems.length) throw new Error(`${file} does not embed dist/:\n  ${summarize(problems)}`);
    console.log(`${file}: embedded web content equals dist/ (manifest sha256:${manifestDigest(manifest(DIST))})`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function cmdSync() {
  requireDist();
  cmdVersion(false);
  const r = spawnSync('npx', ['--no-install', 'cap', 'sync'], { cwd: MOBILE, stdio: 'inherit' });
  if (r.status !== 0) throw new Error('`cap sync` failed');
  const digest = cmdVerify();
  mkdirSync(join(MOBILE, 'build'), { recursive: true });
  const lock = readLock();
  writeFileSync(join(MOBILE, 'build/web-manifest.json'), JSON.stringify({
    courseVersion: lock.courseVersion, onoCommit: lock.onoCommit, files: manifest(DIST), sha256: digest,
  }, null, 2) + '\n');
}

function cmdInfo() {
  const lock = readLock();
  const rev = readVersionJson().buildRevision;
  const code = buildNumbers(lock.courseVersion, rev);
  const pkg = JSON.parse(readFileSync(join(MOBILE, 'package.json'), 'utf8'));
  const vars = readFileSync(join(MOBILE, 'android/variables.gradle'), 'utf8');
  const num = (n) => new RegExp(`${n}\\s*=\\s*(\\d+)`).exec(vars)?.[1];
  const pbx = readFileSync(PBXPROJ, 'utf8');
  const baseline = JSON.parse(readFileSync(join(MOBILE, 'baseline.json'), 'utf8'));
  const info = {
    course: { version: lock.courseVersion },
    onoSendai: { version: lock.onoVersion, commit: lock.onoCommit },
    capacitor: pkg.dependencies['@capacitor/core'],
    plugins: Object.entries(pkg.dependencies).filter(([n]) => !/core|android|ios/.test(n)),
    android: { applicationId: JSON.parse(readFileSync(join(MOBILE, 'capacitor.config.json'), 'utf8')).appId, versionName: lock.courseVersion, versionCode: code, minSdk: Number(num('minSdkVersion')), compileSdk: Number(num('compileSdkVersion')), targetSdk: Number(num('targetSdkVersion')) },
    apple: { bundleId: /PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);/.exec(pbx)?.[1], shortVersion: lock.courseVersion, build: String(code), deploymentTarget: /IPHONEOS_DEPLOYMENT_TARGET = ([\d.]+);/.exec(pbx)?.[1], minXcode: baseline.apple.minXcode },
    buildRevision: rev,
  };
  console.log(JSON.stringify(info, null, 2));
}

const [cmd, ...args] = process.argv.slice(2);
try {
  if (cmd === 'sync') cmdSync();
  else if (cmd === 'verify') cmdVerify();
  else if (cmd === 'verify-package') cmdVerifyPackage(args[0]);
  else if (cmd === 'info') cmdInfo();
  else if (cmd === 'version') cmdVersion(args.includes('--check'));
  else throw new Error('usage: mobile.mjs sync | verify | verify-package <file> | info | version [--check]');
} catch (e) {
  console.error(`mobile: ${e.message}`);
  process.exit(1);
}
